server:
  port : 8082

spring:
  data:
    mongodb:
      host: mongodb
      port: 27017
      authentication-database: admin
      database: macaw
      username: admin
      password: sa
  mvc:
    static-path-pattern: "/resources/images/**"